version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: goldenwaste_db
      MYSQL_USER: goldenuser
      MYSQL_PASSWORD: newpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  app:
    image: cyberinu81/tawazun
    container_name: tawazun_container
    depends_on:
      - mysql
    networks:
      - my_network
    environment:
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"

networks:
  my_network:
    driver: bridge

